### ISSUE TITLE
[ Layout ] Correções na sidebar de casos

### ISSUE THREAD

**Issue by MoisesMsa** [conselhoindigenistamissionario/caci#10]
- [x] Mudar background do input de pesquisa
- [x] Alterar background do número de resultados encontrados
- [x]  Adicionar sombra no texto de número de resultados
- [x]   Mover a cidade/estado para baixo do título
- [x]  Adicionar ícone de map maker ao lado da cidade/estado
- [x] Alterar cor do ícone de calendário e data
- [x]  Ajustar espaçamento dos títulos

Layout:

![Screenshot from 2021-09-17 17-09-40](https://user-images.githubusercontent.com/16871448/133848081-821b7d1f-6c70-4ce1-b8b5-5c61fe394166.png)

**Comment by willowmagrini** [comment]
@MoisesMsa a largura do sidebar me parece maior no dev que no layout, acho que vale reduzir.

**Comment by MoisesMsa** [comment]
@willowmagrini subi essa correção

**Comment by willowmagrini** [comment]
- [ ] Largura ainda não esta como no layout (ta com max-width:420px mas não esta pegando as 420px)
- [ ] tamanho da fonte do titulo do caso diferente do layout
