### ISSUE TITLE
Verificar se o storymap esta funcionando

### ISSUE THREAD

**Issue by willowmagrini** [conselhoindigenistamissionario/caci#2]

**Comment by matheusgimenez** [comment]
https://caci.hacklab.com.br/storymap/2389-2/

Precisa corrigir o header para funcionar perfeitamente.

**Comment by matheusgimenez** [comment]
Após algumas correções rápidas, o storymap passou a funcionar. Porem, existe elementos faltantes nessa página e que levaria algumas horas para serem desenvolvidos (uma vez que esta página não é gerada pelo Angular), esses elementos são:

- Menu "hamburguer"
- Botão de compartilhar
- Modal do botão de compartilhar

# Outros itens necessários a pensar
- Atualmente o storymap não está listado em nenhum local do layout, é necessário definir onde será "linkado" o acesso para cada storymap, se será exibido o archive deste tipo de post e com qual layout, uma vez que isto não está definido.
