### ISSUE TITLE
Testar versão do PHP suportada pelo Wordpress.

### ISSUE THREAD

**Issue by estercmandrade** [conselhoindigenistamissionario/caci#61]
PHP: o ambiente está com uma versão insegura, a 7.3.4, e a versão mínima suportada pelo WordPress é a 7.4. Atualizar para esta versão não deve dar nenhum problema, mas vocês poderiam já tentar subir até a versão 8.0 ou 8.1. Ao menos o plugin do JEO temos certeza que funciona bem com a versão 8.1.6 do PHP porque estamos usando ela nos sites da EJN

**Comment by leopiccionia** [comment]
Estou rodando o PHP 7.4, com WordPress 6.1, no meu local e está funcionando bem.

Não sei se temos uma imagem com PHP 8.

**Comment by leopiccionia** [comment]
Consegui botar para rodar no PHP 8.0. Com 8.1 e 8.2 há muitas incompatibilidades com os plugins.
