### ISSUE TITLE
Erros nos dossiês da Caci e na página de dados abertos

### ISSUE THREAD

**Issue by estercmandrade** [conselhoindigenistamissionario/caci#63]
- [x] [Um genocídio em curso no Mato Grosso do Sul](https://caci.cimi.org.br/#!/dossie/968/?loc=-20.612219573881,-56.568603515625,6&init=true)
Erro ao abrir os casos filtrados - o filtro funciona, mas a ficha de visualização não.

- [x] [A remoção forçada do povo Pataxó Hã-Hã-Hãe](https://caci.cimi.org.br/#!/dossie/910/?loc=-14.689688902640798,-63.90650246011499,4&init=true)
Os casos de violência deste mapa também não abrem.

- [ ] [O campo de concentração de índios de Minas Gerais](https://caci.cimi.org.br/#!/dossie/977/?loc=-14.647368383896618,-63.89648437500001,4&init=true)
Além das camadas quebradas do mapa, as tabelas do datawrapper incorporadas ao post não estão funcionando.

- [ ] [Waimiri-Atroari, um povo no caminho da Ditadura](https://caci.cimi.org.br/#!/dossie/914/?loc=-0.26210725046521,-61.897087549109,6&init=true)
O mesmo caso do anterior: camadas quebradas no mapa e tabelas do datawrapper incorporadas ao post sem funcionar.

- [ ] Dados abertos
Os links para os [dados abertos](https://caci.cimi.org.br/#!/p/942/) dos dossiês sobre O campo de concentração de índios de Minas Gerais ([este link](https://caci.cimi.org.br/dadosabertos/dossies/indigenas_presos_ditadura.zip)) e Waimiri-Atroari, um povo no caminho da Ditadura ([este link](https://caci.cimi.org.br/dadosabertos/dossies/terra_waimiri-atroari.zip)) não estão funcionando.

- [x] As legendas não aparecem: apesar de definidas nas configurações do mapa, as legendas não estão aparecendo. A referência é o mapa do dossiê Waimiri-Atroari.

**Comment by leopiccionia** [comment]
No dossiê sobre MG, não achei datawrappers quebrados. Achei um no dossiê Waimiri-Atroari.

**Comment by estercmandrade** [comment]
https://datawrapper.dwcdn.net/Je4M1/5/

https://datawrapper.dwcdn.net/oEswz/2/

https://datawrapper.dwcdn.net/xbXJh/2/
