### ISSUE TITLE
Correção de erros de importação

### ISSUE THREAD

**Issue by leopiccionia** [conselhoindigenistamissionario/caci#71]
## Bugs

- [x] Investigar erros 502 ao importar CSV
- [x] Investigar erros 502 ao editar casos
- [x] Investigar erros de geolocalização

**Comment by estercmandrade** [comment]
![Captura de Tela 2023-10-06 às 14 05 39](https://github.com/conselhoindigenistamissionario/caci/assets/91154843/dbbbb3fb-665b-4c38-9dfc-b6f2e3b83565)
