### ISSUE TITLE
[PENDÊNCIAS] Mapa - ajustes gerais

### ISSUE THREAD

**Issue by estercmandrade** [conselhoindigenistamissionario/caci#83]
Mapa

- [x] Ajustar altura do botão zoom out zoom in ao lado direito (está sendo exibido cortado atrás do cabeçalho).
- [x] Exibir ícones de CAMADAS e LEGENDAS.
- [x] Mapa está listando apenas os casos de violência contra pessoa.

**Comment by leopiccionia** [comment]
Sobre o terceiro ponto: os outros casos ainda não foram importados.
